### ISSUE TITLE
Line feed necessary

### ISSUE THREAD

**Issue by unlocomqx** [hxlniada/webpack-concat-plugin#1]
Sometimes concat results in a syntax error
```
//# sourceMappingURL=payapi-error-dialog.js.map|webpackJsonp([1],{

/***/ 1:
/***/ (function(module, exports, __webpack_require__) {
```

The pipe indicates where the prev file ends and new file starts

Disabling source maps solves the problem but I wanted to let you know
`devtool: false,`

Maybe test on the devtool flag and add a Line Feed if it's not false

**Comment by hxlniada** [comment]
I use it with config devtool: 'source-map' and workes well. Can you show me all of your config and you node version?

**Comment by hxlniada** [comment]
update to 1.1.1 and have a try
