### ISSUE TITLE
filesToConcat - avoid direct list of files

### ISSUE THREAD

**Issue by denis-andrikevich** [hxlniada/webpack-concat-plugin#17]
Hi, there. 
Can i just use instead of :
```
filesToConcat: [
   '/path/to/file1.js',
   '/path/to/file2.js',
   '/path/to/file3.js',
]
```
something like that:
```
filesToConcat: {
   recursive: true,
   path: '/path/to/*.js'
}

```

**Comment by rebolyte** [comment]
@denis-andrikevich It would be easy enough to do this yourself with [glob](https://github.com/isaacs/node-glob): `filesToConcat: glob.sync('/path/to/**/*.js')`

**Comment by GlenHughes** [comment]
@rebolyte, are you able to do this a PR so I could introduce it into my code?

**Comment by hxlniada** [comment]
I'll add this feature soon.

**Comment by denis-andrikevich** [comment]
@rebolyte forgot to reply, thx a lot 👍
