### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by subhaze** [hxlniada/webpack-concat-plugin#2]
@hxlniada, First, thanks for this plugin!

I've found an issue where building in production mode but not generating source maps throws the error `Cannot read property 'toString' of null`, this appears to be cause by the following line https://github.com/hxlniada/webpack-concat-plugin/blob/master/index.js#L67 since it's asking for the source maps, but, there are none.

**Comment by hxlniada** [comment]
thank you, i'll fix this soon later
