### ISSUE TITLE
Implement hook from webpack-manifest-plugin 2.0.0-rc.1

### ISSUE THREAD

**Issue by Levdbas** [hxlniada/webpack-concat-plugin#22]
Usecase:

I have a lot of legacy code that I concat via this plugin. I also hash the filenames for cache busting. The guys from the webpack-manifest plugin included a hook that can be used by other plugins to use. This will add your output file(s) to the manifest. Would it be an idea to implement it?

see also: https://github.com/danethurber/webpack-manifest-plugin/pull/76

**Comment by hxlniada** [comment]
Good idea, I will try it.
BTW, feel free to push a pr if you have time 🙂.

**Comment by hxlniada** [comment]
update to 2.0.0 and try again，there is a manifestName option, 🙂

**Comment by Gibbs** [comment]
Looks like this was removed a few days later in https://github.com/hxlniada/webpack-concat-plugin/commit/637ca25ccc45ef2763ca73f1bf647aee8dda093c

Is there any way for this plugin to work with webpack-manifest-plugin?

**Comment by hxlniada** [comment]
@Gibbs it works automatically
