### ISSUE TITLE
Remove process.env.NODE_ENV

### ISSUE THREAD

**Issue by var-bp** [hxlniada/webpack-concat-plugin#24]
Hello, I want to say thank you so much for this plugin. But I have problem with it. `process.env.NODE_ENV === 'production' ` is excessive and minify the bundle on production when you don't need it. Can you remove it? `self.settings.uglify` is sufficient check. Also `[hash]` don't respond for shortened version like `[hash:8]`. Can you fix it, please?

**Comment by hxlniada** [comment]
update to 2.0.0 and try again. 🙂
