### ISSUE TITLE
Plese сompress files separately

### ISSUE THREAD

**Issue by retyui** [hxlniada/webpack-concat-plugin#25]
Due to the fact that the file is very large, the UglifyJS compresses with errors
https://github.com/hxlniada/webpack-concat-plugin/blob/master/index.js#L98

**Comment by hxlniada** [comment]
can you show me the error logs? thank you.

**Comment by retyui** [comment]
```
WARN: Output exceeds 32000 characters
```
Browser error after compres js:
```
Type error : e is undefined ...
```

**Comment by hxlniada** [comment]
can I get your file and test it, as far as i know  the warning should not effect the result.

**Comment by hxlniada** [comment]
hello, has uglify-es solved  your problem?

**Comment by retyui** [comment]
@hxlniada Yes , problem solved!
