### ISSUE TITLE
`sourceMap` option does not work with `uglify: false`

### ISSUE THREAD

**Issue by jaketodaro** [hxlniada/webpack-concat-plugin#28]
If you're not uglifying then the sourcemap option is completely ignored. If you'll accept a PR using https://www.npmjs.com/package/concat-with-sourcemaps to do the concat if you're not using uglify then I'd be happy to work on this.

**Comment by hxlniada** [comment]
yes, feel free to send a pr, thank you.

**Comment by dcherman** [comment]
Thanks @jaketodaro!
