### ISSUE TITLE
How to inject script name into specific chunk or file?

### ISSUE THREAD

**Issue by pbastowski** [hxlniada/webpack-concat-plugin#51]
Is there a way to tell the concat plugin into which chunk or html file to inject the script it generates?

I have a webpack config with multiple entries, each of which results in a separate emitted html file.
I use the concat-plugin to build separate vendor scripts for each of the entries. The problem I am having is that each of the emitted html files is injected with all of the vendor scripts.

So, the config consists of this:

```js
entry: {
    client:      'index.js',
    user:        'index-user.js',
 }
```

And the concat plugins are configured like this

```js
// For index.js
new ConcatPlugin({
    name:          'vendor-js',
    fileName:      '[name].[hash:8].js',
    filesToConcat: [ vendor_files.js ],
}),

// For index-user.js
new ConcatPlugin({
    name:          'vendor-user-js',
    fileName:      '[name].[hash:8].js',
    filesToConcat: [ vendor_files.jsUser ],
}),
```

Currently, there are two index.html files generated, `index.html` and `index-user.html`, both of which include both concatenated scripts, like so:

```html
    <script type="text/javascript" src="/vendor-js.c8e444ce.js"></script>
    <script type="text/javascript" src="/vendor-user-js.c9e464ce.js"></script>
```

I need index.html to only include 
```html
    <script type="text/javascript" src="/vendor-js.c8e444ce.js"></script>
```
and index-user.htlm to include this
```html
    <script type="text/javascript" src="/vendor-user-js.c9e464ce.js"></script>
```

Thanks.

**Comment by pbastowski** [comment]
I just noticed this old issue of mine that no one was able to answer. I figured it out months ago and, in case anyone is wondering how I did this, below is what I did. I don't claim this to be the best approach, it's just what worked for me.

**Do it manually**

1) Tell ConcatPlugin not to inject anything about these files into the generated html files.

```js
// For index.js
new ConcatPlugin({
    name:          'vendor-js',
    injectType:  'none',
    fileName:     '[name].[hash:8].js',
    filesToConcat: [ vendor_files.js ],
}),

// For index-user.js
new ConcatPlugin({
    name:          'vendor-user-js',
    injectType:  'none',
    fileName:     '[name].[hash:8].js',
    filesToConcat: [ vendor_files.jsUser ],
}),
```

2) Next, in my `index.ejs` template file, just before `</body>`, I added the following lines that **inject** what I need where I need.

```html
    <%
        let filename = htmlWebpackPlugin.options.filename
        let entry = (filename.match(/.*-(.+?)\.html/i)||[])[1] || ''
        let inject_file = htmlWebpackPlugin.files.webpackConcat[`vendor${entry && '-'}${entry}-js`]
    %>
    <script type="text/javascript" src="<%= inject_file %>"></script>
</body>
```

**Comment by Krustal** [comment]
Thank you very much for coming back to post this solution
