### ISSUE TITLE
Allow templating fileName

### ISSUE THREAD

**Issue by filipesilva** [hxlniada/webpack-concat-plugin#9]
This is a feature request.

When configuring Webpack output, it is possible to specify a couple of template variables like `[name].[hash].bundle.js`.

In `webpack-concat-plugin` this is not possible, and the hash is always positioned just before `.js`.

I'd like to request that this be possible in the configuration, falling back to the previous behaviour if the template tags aren't found.

```
new ConcatPlugin({
    // ...
    useHash: true,
    name: 'flexible',
    fileName: '[name].[hash].bundle.js', // would output to 'flexible.d41d8cd98f00b204e980.bundle.js'
});
```

I'd like to work on this feature if you accept the idea.

**Comment by filipesilva** [comment]
PR is up in https://github.com/hxlniada/webpack-concat-plugin/pull/11

**Comment by hxlniada** [comment]
sounds good, thank you

**Comment by filipesilva** [comment]
Thank you.
